---
title: "Workflowr page from the DTU paper"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website hosts code for the paper "Dividing out quantification uncertainty enables assessment of differential transcript usage with limma and edgeR" by Baldoni et al. (2025), which presents optimized differential transcript usage (DTU) pipelines using the the R/Bioconductor packages [edgeR](https://bioconductor.org/packages/release/bioc/html/edgeR.html) and [limma](https://bioconductor.org/packages/release/bioc/html/limma.html). 

The bioRxiv preprint version of the paper can be accessed from https://doi.org/10.1101/2025.04.07.647659.

The presented pipeline builds upon the latest developments of `edgeR` and `limma` with a unified interface via the `diffSplice` function. The pipelines make use of [divided counts](https://doi.org/10.1093/nar/gkad1167) to remove the RTA-induced dispersion and account for the sparsity from transcript-level counts. The new `diffSplice` pipelines provide greater power, improved efficiency, and improved FDR control compared to existing specialized DTU methods.

## Simulation study

The pages below present the necessary steps to rerun our simulation study and the code used to generate the figures and tables from the main and supplementary texts of the DTU paper.

* [Rerunning the simulation studies](simulation-howto.html)
* [Results from the main paper (Figures 1--4)](main-simulation.html)
* [Results from the supplement contrasting BCV plots (Supplementary Figure S1)](supp-bcv.html)
* [Results from the supplement with strict filtering and raw counts (Supplementary Figures S2--S7)](supp-simulation-rawcounts.html)
* [Results from the supplement with strict filtering and divided counts (Supplementary Figures S8--S14)](supp-simulation-dividedcounts.html)
* [Results from the supplement for BANDITS (Supplementary Figures S15--S16)](supp-simulation-bandits.html)
* [Results results from the supplement with lenient filtering (Supplementary Tables S1--S2)](supp-simulation-lenient.html)

## Case study

The pages below present the data pre-processing steps and analysis report of the RNA-seq experiments from the steady-state adult mouse mammary gland (GEO accession [GSE227748](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE227748)).

* [Data pre-processing](mouse-howto.html)
* [Results from the main paper (Figure 5)](main-casestudy.html)
