---
title: "Rerunning the simulation study"
author: "Pedro Baldoni"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

The R code used in our simulation study to generate the simulated data, quantify the FASTQ files, run DTU methods, and summarize the results was organized as an R package and it is located in the GitHub repository of this page in the directory `./code/pkg`.

In our paper, we have run one simulation study and analyzed it in two ways: one with a more restrictive filtering criteria ("strict", with default arguments in the *filterByExpr* function) and another with a more permissive filtering criteria ("lenient"), as described in our paper. In our repository, scripts to reproduce these two simulation studies are located in the directories `./code/simulation-no-trend` and `./code/simulation-lenient-no-trend`, respectively. Instructions on how to run these simulation studies are identical. Below I describe how to run the "strict" simulation. Analogous steps can be followed to reproduce the lenient simulation.

To run our simulations, readers should refer to the files stored in the directory `./code/simulation-no-trend`. The text file `./code/simulation-no-trend/readme.txt` presents the necessary steps to run the simulations and summarize the results. Briefly, readers should run the following steps:

1. Run the file `parameters.R` with, for example, the command `Rscript parameters.R`.

2. Run the SLURM script `run.sh` with, for example, `sbatch run.sh` on your HPC running the SLURM workload manager. If your HPC uses a different workload manager, please change `run.sh` accordingly.

3. Once all simulations have been completed, run the script `summarize.R` with, for example, the command `Rscript summarize.R` to summarize all the results.

Once steps 1-3 above have been completed, the Rmarkdown `main-simulation.Rmd` file under `./analysis`, for example, can be run.
